id: I96402432
legacy_id: P000386
ocr_import_info:
  bdrc_scan_id: W23450
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T13:41:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:07:14.414777+00:00'
last_modified: 2022-09-02 09:07:31.810051
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23450
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23450
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་ཡུལ་ཆོས་སྤྱོད་༔་ཅོལླེཅཏེད་ལིཏུརྒིཅལ་ཏེ྾ཙ་རེཅིཏེད་ཨཏ་ཐེ་མོནསྟེརཡ་དཔལ་ཡུལ་ཨིན་ཁམས།
statistics:
  ocr_word_mean_confidence_index: 0.6039279537912031
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I1KG1377:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1377
      total_pages: 880
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1377.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6039279537912031
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
